_target_: models.latent_generators.mingpt.MinGPT
input_dim: ${action_interface.encoder.output_dim}
action_dim: ${env.action_dim}
block_size: ${experiment.window_size}  # Length of history/context
discrete_input: False
predict_offsets: True

# Pick cross validation run model
load_dir: "/absolute/path/to/training_run/directory"
